[build]
  command = "npm run build --workspace client"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/okrApi/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
